linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gomoddirectives:
    replace-local: true
linters:
  enable-all: true
  fast: false
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - goerr113
    - maintidx
    - nestif
    - nonamedreturns
    - tagliatelle
    - maligned
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "mnd: Magic number: 2, in"
    - "mnd: Magic number: 3, in"
    - "mnd: Magic number: 10, in"
