version: "2"
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
  settings:
    funlen:
      lines: 160
      statements: 85
    gocognit:
      min-complexity: 45
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 35
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'Magic number: 2, in'
      - path: (.+)\.go$
        text: 'Magic number: 3, in'
      - path: (.+)\.go$
        text: 'Magic number: 10, in'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
