linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 35
  funlen:
    lines: 160
    statements: 85
  gomoddirectives:
    replace-local: true
  gocognit:
    min-complexity: 45
  govet:
    enable-all: true
linters:
  enable-all: true
  fast: false
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    # deprecated
    - execinquery
    - gomnd
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: true
  exclude:
    - "Magic number: 2, in"
    - "Magic number: 3, in"
    - "Magic number: 10, in"
    - "fieldalignment: struct"
