linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gomoddirectives:
    replace-local: true
  govet:
    check-shadowing: true
linters:
  enable-all: true
  fast: false
  disable:
    - cyclop
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - ifshort
    - interfacer
    - maligned
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    # deprecated
    - deadcode
    - structcheck
    - varcheck
    - scopelint
    - nosnakecase
    - golint
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: true
  exclude:
    - "mnd: Magic number: 2, in"
    - "mnd: Magic number: 3, in"
    - "mnd: Magic number: 10, in"
